- name: Подготовка узлов
  become: true
  hosts:
  - patroni_postgresql_cluster
  roles:
  - docker_install
  tasks:
  - name: Создаю пользователя
    ansible.builtin.user:
      name: '{{ patroni_user }}'
      uid: '{{ patroni_uid }}'
      shell: /usr/sbin/nologin
      groups:
      - docker

- name: Подготовка кластера
  become: true
  hosts:
  - patroni_postgresql_cluster
  roles:
  - etcd
  - patroni
