#!/usr/bin/env bash
# =============================================================================
# Boot the three Lima VMs that back the Patroni integration test and generate
# the ansible inventory that targets them.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANSIBLE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
NODE_CONFIG="$SCRIPT_DIR/../lima-node.yaml"
INVENTORY="$SCRIPT_DIR/../inventory.lima.yaml"

NODES=(patroni-postgresql-01 patroni-postgresql-02 patroni-postgresql-03)

# Lima mirrors the host username as the default guest user, so derive it here
# instead of hardcoding. Keeps the harness portable across host users.
HOST_USER="$(whoami)"

# -----------------------------------------------------------------------------
# 1. Create / start the three VMs.
# -----------------------------------------------------------------------------
echo "==> Starting Lima nodes..."
for node in "${NODES[@]}"; do
  if limactl list -q | grep -qx "$node"; then
    echo "    $node: already exists — starting..."
    limactl start "$node"
  else
    echo "    $node: creating from lima-node.yaml..."
    limactl start --name="$node" "$NODE_CONFIG"
  fi
done

# -----------------------------------------------------------------------------
# 2. Wait for each node to acquire a user-v2 IP (192.168.104.0/24).
# -----------------------------------------------------------------------------
echo "==> Waiting for user-v2 IPs (192.168.104.0/24)..."
declare -a NODE_IPS=()
declare -a SSH_PORTS=()

for node in "${NODES[@]}"; do
  ip=""
  for _ in $(seq 1 120); do
    ip="$(limactl shell "$node" -- bash -lc "ip -4 -o addr show | awk '{print \$4}' | cut -d/ -f1 | grep '^192\.168\.104\.' | head -1" 2>/dev/null || true)"
    if [[ -n "$ip" ]]; then
      break
    fi
    sleep 1
  done

  if [[ -z "$ip" ]]; then
    echo "ERROR: $node did not acquire a user-v2 IP within 120s" >&2
    exit 1
  fi

  # Discover the forwarded SSH local port for this instance.
  if command -v jq >/dev/null 2>&1; then
    port="$(limactl list --json "$node" | jq -r '.sshLocalPort')"
  else
    port="$(limactl list --json "$node" | python3 -c 'import sys,json;print(json.load(sys.stdin)["sshLocalPort"])')"
  fi

  echo "    $node: user-v2 IP=$ip  ssh_port=$port"
  NODE_IPS+=("$ip")
  SSH_PORTS+=("$port")
done

# -----------------------------------------------------------------------------
# 3. Generate the ansible inventory.
# -----------------------------------------------------------------------------
echo "==> Generating $INVENTORY ..."
{
  echo "# Generated by scripts/up.sh — do not edit. Re-run up.sh to regenerate."
  echo "patroni_postgresql_cluster:"
  echo "  hosts:"
  for i in "${!NODES[@]}"; do
    node="${NODES[$i]}"
    ip="${NODE_IPS[$i]}"
    port="${SSH_PORTS[$i]}"
    cat <<EOF
    $node:
      ansible_host: 127.0.0.1
      ansible_port: $port
      ansible_user: $HOST_USER
      ansible_ssh_private_key_file: ~/.lima/_config/user
      patroni_node_address: $ip
EOF
  done
  echo "  vars:"
  echo "    ansible_python_interpreter: /usr/bin/python3"
} > "$INVENTORY"

echo ""
echo "==> All three nodes are up and inventory.lima.yaml is ready."
echo ""
echo "Next step — deploy the cluster:"
echo "  cd \"$ANSIBLE_DIR\" && ansible-playbook -i tests/lima/inventory.lima.yaml patroni_postgresql_cluster.yaml"
