  - name: Add Docker apt repository
    ansible.builtin.deb822_repository:
      name: docker
      types: deb
      uris: https://download.docker.com/linux/ubuntu
      suites: '{{ ansible_distribution_release }}'
      components: stable
      signed_by: https://download.docker.com/linux/ubuntu/gpg

  - name: Install packages
    ansible.builtin.apt:
      name:
        - docker-ce
      state: present
      update_cache: true

  - name: Gather package facts
    ansible.builtin.package_facts:

  - name: Copy daemon.json
    ansible.builtin.copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      mode: '644'
    notify:
      - Restart docker.service
