- name: Set mode for directory
  ansible.builtin.file:
    path: /var/lib/etcd
    state: directory
    owner: '{{ patroni_uid }}'
    group: '{{ patroni_uid }}'

- name: Copy unit file etcd
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify:
  - Restart etcd.service

- name: Setup etcd.service
  ansible.builtin.systemd:
    name: etcd.service
    state: started
    enabled: true
